<script setup lang="ts">
import { computed } from "vue";
import { formatINR } from "@/composables/useTax";

interface Scenario {
  id: string;
  name: string;
  description?: string;
  selectedRegime: string;
  totalGrossIncome: number;
  totalDeductions: number;
  taxableIncome: number;
  totalTaxLiability: number;
  taxDifferenceFromBaseline: number;
  percentageSavings: number;
  isAutoGenerated?: boolean;
  optimizationCategory?: string;
}

const props = defineProps<{
  scenario: Scenario;
  baseline: Scenario | null;
  selected?: boolean;
}>();

const emit = defineEmits<{
  (e: "edit"): void;
  (e: "delete"): void;
  (e: "toggle-compare"): void;
}>();

const isBetter = computed(() => {
  return props.scenario.taxDifferenceFromBaseline < 0;
});

const isWorse = computed(() => {
  return props.scenario.taxDifferenceFromBaseline > 0;
});

const savingsAmount = computed(() => {
  return Math.abs(props.scenario.taxDifferenceFromBaseline);
});

const savingsPercent = computed(() => {
  return Math.abs(props.scenario.percentageSavings);
});

function getCategoryIcon(category?: string): string {
  const icons: Record<string, string> = {
    MAX_80C: "mdi-piggy-bank",
    MAX_NPS: "mdi-bank",
    MAX_80D: "mdi-medical-bag",
    REGIME_SWITCH: "mdi-swap-horizontal",
    COMBINED_OPTIMAL: "mdi-star",
  };
  return icons[category || ""] || "mdi-file-document";
}

function getCategoryColor(category?: string): string {
  const colors: Record<string, string> = {
    MAX_80C: "purple",
    MAX_NPS: "blue",
    MAX_80D: "green",
    REGIME_SWITCH: "orange",
    COMBINED_OPTIMAL: "amber",
  };
  return colors[category || ""] || "grey";
}
</script>

<template>
  <v-card
    :class="{
      'border-success': selected && isBetter,
      'border-warning': selected && isWorse,
      'border-primary': selected && !isBetter && !isWorse,
    }"
    :variant="selected ? 'outlined' : 'elevated'"
    class="scenario-card"
  >
    <!-- Header -->
    <v-card-title class="d-flex align-center pb-0">
      <div class="flex-grow-1">
        <div class="d-flex align-center">
          <span class="text-body-1 font-weight-medium">{{ scenario.name }}</span>
          <v-chip
            v-if="scenario.isAutoGenerated"
            size="x-small"
            color="info"
            variant="tonal"
            class="ml-2"
          >
            <v-icon start size="x-small">mdi-magic-staff</v-icon>
            Auto
          </v-chip>
        </div>
      </div>
      <v-checkbox
        :model-value="selected"
        hide-details
        density="compact"
        color="primary"
        @update:model-value="emit('toggle-compare')"
      />
    </v-card-title>

    <v-card-subtitle v-if="scenario.description" class="pb-2">
      {{ scenario.description }}
    </v-card-subtitle>

    <v-card-text>
      <!-- Regime Badge -->
      <div class="mb-3">
        <v-chip
          :color="scenario.selectedRegime === 'NEW' ? 'primary' : 'secondary'"
          size="small"
          variant="tonal"
        >
          {{ scenario.selectedRegime === 'NEW' ? 'New Regime' : 'Old Regime' }}
        </v-chip>
        <v-chip
          v-if="scenario.optimizationCategory"
          :color="getCategoryColor(scenario.optimizationCategory)"
          size="small"
          variant="tonal"
          class="ml-1"
        >
          <v-icon start size="x-small">
            {{ getCategoryIcon(scenario.optimizationCategory) }}
          </v-icon>
          {{ scenario.optimizationCategory.replace('MAX_', '').replace('_', ' ') }}
        </v-chip>
      </div>

      <!-- Key Metrics -->
      <v-row dense>
        <v-col cols="6">
          <div class="text-caption text-medium-emphasis">Taxable Income</div>
          <div class="text-body-2 font-weight-medium text-currency">
            {{ formatINR(scenario.taxableIncome) }}
          </div>
        </v-col>
        <v-col cols="6">
          <div class="text-caption text-medium-emphasis">Tax Liability</div>
          <div class="text-body-2 font-weight-bold text-currency">
            {{ formatINR(scenario.totalTaxLiability) }}
          </div>
        </v-col>
      </v-row>

      <!-- Comparison to Baseline -->
      <v-divider class="my-3" />

      <div class="comparison-section">
        <div class="d-flex align-center justify-space-between">
          <span class="text-caption text-medium-emphasis">vs Baseline</span>
          <div>
            <v-chip
              v-if="isBetter"
              color="success"
              size="small"
              prepend-icon="mdi-arrow-down"
            >
              Save {{ formatINR(savingsAmount) }}
            </v-chip>
            <v-chip
              v-else-if="isWorse"
              color="error"
              size="small"
              prepend-icon="mdi-arrow-up"
            >
              +{{ formatINR(savingsAmount) }}
            </v-chip>
            <v-chip v-else color="grey" size="small">
              No Change
            </v-chip>
          </div>
        </div>

        <div v-if="savingsPercent > 0" class="text-caption text-medium-emphasis mt-1">
          {{ savingsPercent.toFixed(1) }}% {{ isBetter ? 'less' : 'more' }} tax
        </div>
      </div>
    </v-card-text>

    <!-- Actions -->
    <v-card-actions>
      <v-btn
        variant="text"
        size="small"
        prepend-icon="mdi-pencil"
        @click="emit('edit')"
      >
        Edit
      </v-btn>
      <v-spacer />
      <v-btn
        variant="text"
        size="small"
        color="error"
        icon="mdi-delete"
        @click="emit('delete')"
      />
    </v-card-actions>
  </v-card>
</template>

<style scoped>
.scenario-card {
  height: 100%;
  display: flex;
  flex-direction: column;
}

.scenario-card .v-card-text {
  flex-grow: 1;
}

.comparison-section {
  background: rgba(var(--v-theme-surface-variant), 0.3);
  padding: 8px 12px;
  border-radius: 8px;
}
</style>
